### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.codecs.Codec$Holder

### ISSUE THREAD

**Issue by guotong1988** [agile-lab-dev/sparksearchengine#3]
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.codecs.Codec$Holder
        at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
        at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:111)
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:132)
        at it.agilelab.bigdata.spark.search.impl.LuceneIndexedPartition$.buildIndexWriterConfig(LuceneIndexedPartition.scala:208)
        at it.agilelab.bigdata.spark.search.impl.DistributedIndexLuceneRDD$.it$agilelab$bigdata$spark$search$impl$DistributedIndexLuceneRDD$$createIndex(DistributedIndexLuceneRDD.scala:597)
        at it.agilelab.bigdata.spark.search.impl.DistributedIndexLuceneRDD$$anonfun$67.apply(DistributedIndexLuceneRDD.scala:521)
        at it.agilelab.bigdata.spark.search.impl.DistributedIndexLuceneRDD$$anonfun$67.apply(DistributedIndexLuceneRDD.scala:521)
```

@nicolobidotti Thank you very much
@matteobovetti Thank you very much

**Comment by guotong1988** [comment]
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/org.apache.lucene.codecs.Codec</resource>
                                </transformer>
                            </transformers>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>fat</shadedClassifierName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
